about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path('about/', about, name='about')
]

grafo/urls.py
from django.contrib import admin
from django.urls import path
from .views import grafo

app_name = 'grafo'

urlpatterns = [

    path('',grafo,name="grafo"),

    
]

home/urls.py
from django.contrib import admin
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [

    path('home/',home,name="home"),

    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from about import views
from sintactico import views
from grafo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('sintactico.urls')),
    path('', include('grafo.urls')),
    
]

sintactico/urls.py
from django.urls import path
from .views import sintactico

#app_name = AppName

urlpatterns = [
    path('sintactico/', sintactico, name="sintactico")
]

about/models.py
from django.db import models

# Create your models here.

grafo/models.py
from django.db import models

class Paciente(models.Model):
    name=models.CharField(max_length=50)
    
    class Meta:
        verbose_name = ("Paciente")
        verbose_name_plural = ("Pacientes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})

class Tessiu(models.Model):
    temperatura = models.FloatField()
    color = models.FloatField()
    inflamation = models.FloatField(verbose_name="Inflamacion")
    name = models.ForeignKey(Paciente,blank=True, null=True,verbose_name="Nombre", on_delete=models.CASCADE)
    #fieldName = models.ManyToManyField(RelatedModel)
    #fieldName = models.OneToOneField(RelatedModel, on_delete=models.CASCADE)
    
    
     
    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura) + "   " 
        else:
           return str(self.temperatura)   
    

    def get_absolute_url(self):
        return reverse("Tessiu_detail", kwargs={"pk": self.pk})

home/models.py
from django.db import models

class Paciente(models.Model):
    name=models.CharField(max_length=50)
    
    class Meta:
        verbose_name = ("Paciente")
        verbose_name_plural = ("Pacientes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})

class Tessiu(models.Model):
    temperatura = models.FloatField()
    color = models.FloatField()
    inflamation = models.FloatField(verbose_name="Inflamacion")
    name = models.ForeignKey(Paciente,blank=True, null=True,verbose_name="Nombre", on_delete=models.CASCADE)
    #fieldName = models.ManyToManyField(RelatedModel)
    #fieldName = models.OneToOneField(RelatedModel, on_delete=models.CASCADE)
     
    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura) + "   " 
        else:
           return str(self.temperatura)   
    

    def get_absolute_url(self):
        return reverse("Tessiu_detail", kwargs={"pk": self.pk})

sintactico/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    template_name = "about/about.html"
    nombre=consultaDB(request)
    lista= [1,2,3,4,5 ]
    return render(request, template_name, {'nombre':nombre,'apellido':"Marcial", 'milista':lista})

def consultaDB(request):
    return "Ruben"
    

grafo/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Tessiu

# Create your views here.
def grafo(request):

    #return HttpResponse("Home")
    
    l= Tessiu.objects.get_queryset()
    template_name = "grafo/grafo.html"
    listaProcesada = procesaLista(l)
    return render(request, template_name, {'lista1':l,'listaproc1':listaProcesada})
    
        
def nohome(request):
    print("SALUDOS A LA BANDA")
    
    return HttpResponse("BANDA")

def procesaLista(lista):
    #Hacer algo con la lista
    lista1=[]
    for elemento in lista:
        valor=elemento.temperatura**2 + elemento.inflamation**2 + elemento.color**2
        p=valor**0.5
        if  p > 100:
            lista1.append(p)
    return lista1

   

home/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Tessiu
import pandas as pd
from scipy.spatial import distance
tessiu = Tessiu.objects.all()

# Create your views here.
def home(request):

    #return HttpResponse("Home")
    
    l= Tessiu.objects.get_queryset()
    template_name = "home/index.html" 
    listaProcesada = procesaLista(l)
    distancia= euclidea(l)
    return render(request, template_name, {'lista':l,'listaproc':listaProcesada,'euclidea':distancia})
    
        
def nohome(request):
    print("SALUDOS A LA BANDA")
    
    return HttpResponse("BANDA")

def procesaLista(lista):
    #Hacer algo con la lista
    lista1=[]
    for elemento in lista:
        valor=elemento.temperatura**2 + elemento.inflamation**2 + elemento.color**2
        p=valor**0.5
        if  p > 100:
            lista1.append(p)
    return lista1

def euclidea(tejidos):
    tejidosTotal = []
    for i in tejidos:
        tejido = []
        tejido.append(i.temperatura)
        tejido.append(i.color)
        tejido.append(i.inflamation)
        tejidosTotal.append(tejido)      

    mEuclidea = []
    for i in range(len(tejidosTotal)):
        f = []
        for j in range(len(tejidosTotal)):
            f.append(round(distance.euclidean(tejidosTotal[i],tejidosTotal[j], 6 )))
        mEuclidea.append(f)

    return mEuclidea

def procesa(request):
    if(request.method == 'POST'):
        umbral = int(request.POST['umbral'])
        
    return render(request, 'index.html' , {'Tessiu': tessiu, 'euclidea':euclidea(tessiu) , 'umbral':umbral})
   

sintactico/views.py
from django.shortcuts import render

# Create your views here.

def sintactico(request):
    
    template_name = "sintactico/sintactico.html"
    return render(request, template_name, {})
    

grafo/templates/grafo/grafo.html
{% extends 'home/index.html' %}
    {% block contenido %}
      <center><a href="https://www.youtube.com/watch?v=-Jx74vZEDDo"><img src="https://www.gob.mx/cms/uploads/article/main_image/44507/li.gif" width="700" height="400" ></a></center>
      <h1><font size="3" style= "color: rgb(163, 9, 184);"><center>HAZ CLICK EN LA IMAGEN PARA VER VIDEO INFORMATIVO</center></font></h1>
      <h1><font size="3" style= "color: rgb(255, 255, 255);"><center>REALIZADO POR ALUMNOS DEL GRUPO: M9:</center></font></h1>
      <h1><font size="3" style= "color: rgb(163, 9, 184);"><center>LOPEZ PINEDA LITZY SARAI</center></font></h1>
      <h1><font size="3" style= "color: rgb(255, 255, 255);"><center>MARCIAL RODRIGUEZ MIGUEL RUBEN</center></font></h1>
      <h1><font size="3" style= "color: rgb(163, 9, 184);"><center>ORTIZ GARCIA SEGIO DAVID</center></font></h1>
  
    {% endblock contenido %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROYECTO RECONOCIMIENTO DE PATRONES SINTACTICO-ESTRUCTURAL</title>


    <script>
      function Numeros(e) {
          key = e.keyCode || e.which;
  
          teclado = String.fromCharCode(key);
  
          numeros = "0123456789";
  
          especiales = "8-37-38-46";
  
          teclado_especial = false;
  
          for (var i in especiales) {
  
              if (key == especiales[i]) {
                  teclado_especial = true;
              }
          }
          if (numeros.indexOf(teclado) == -1 && !teclado_especial) {
              return false
          }
  
  
      }
  </script>

</head>



<body style="background-color: rgb(248, 187, 240);">



  
    <TABLE width= 95% style="border: 5px solid rgb(243, 0, 211); background-color: rgb(255, 255, 255); "  align="center">
        <TR>
            <TD><center><img src="https://fotografias.lasexta.com/clipping/cmsimages02/2013/10/19/13F75B21-1C41-483F-9F1F-E5A7C066F706/58.jpg" width="200" height="100"></center></TD> 
            <TD style="border: 5px solid rgb(255, 98, 221); background-color: rgb(255, 156, 242);" align="center"><a href="{% url  'grafo:grafo' %}" ><font size="5" color="White">Home</font></a></TD> 
            <TD style="border: 5px solid rgb(255, 98, 221); background-color: rgb(255, 156, 242);"align="center"><a href="{% url 'home:home'%}"><font size="5" color="White">Grafo</font></a></TD> 
            <TD style="border: 5px solid rgb(255, 98, 221); background-color: rgb(255, 156, 242);" align="center"><a href="{% url 'about:about' %}"><font size="5" color="White">About</font> </a></TD>
            <TD style="border: 5px solid rgb(255, 98, 221); background-color: rgb(255, 156, 242);" align="center"><a href="{% url 'sintactico' %}"><font size="5" color="White">Sintactico</font></a></TD>
            <TD><center><img src="https://fotografias.lasexta.com/clipping/cmsimages02/2013/10/19/13F75B21-1C41-483F-9F1F-E5A7C066F706/58.jpg" width="200" height="100" ></center></TD> 
        </TR>
    </TABLE>

    

    <h1><center><font size="15" color="White">CURSO DE RECONOCIMIENTO DE PATRONES SINTACTICO ESTRUCTURAL</font></center></h1>
    <h2><center><font size="10" color="White">OCTUBRE MES DEL CANCER DE MAMA</font></center></h2>
    

    



    
{% block contenido %}

<table width= 95% style="border: 5px solid rgb(243, 0, 211); background-color: rgb(255, 156, 242);" align="center">

  <tr>
    <th><center><font size="5" color="White">BASE DE DATOS</font></center></th>
    <!-- <th><center><font size="4" color="White">NORMA</font></center></th> -->
    <th><center><font size="5" color="White">DISTANCIA EUCLIDEA</font></center></th>
    <th><center><font size="5" color="White">RESULTADO DE LOS UMBRALES</font></center></th>
  </tr>

  <tr>
    <td id="nested">
      <table style="width:auto;"  id="BASE DE DATOS" align="center">
        <tr>
          <td>
              {% for elemento in lista %}
              <tr>
                  <th style="border: 5px solid rgb(251, 0, 210);">{{elemento.pk}}</th>
                  {% if elemento.temperatura > 50  %}
                  <th style="border: 5px solid rgb(255, 136, 136);">{{elemento.temperatura}}</th>
                  {% else %}
                  <th style="border: 5px solid rgb(169, 255, 173);">{{elemento.temperatura}}</th>
                  {% endif %}
                  <th style="border: 5px solid rgb(248, 35, 135);">{{elemento.color}}</th>
                  <th style="border: 5px solid rgb(248, 35, 135);">{{elemento.inflamation}}</th>
              </tr>
              {% endfor %}
          </td>
        </tr>
      </table>
    </td>

    <td align="center" valign="top">
      <div id="Layer1" style="width:700px; height:-400px; overflow: scroll;" >
        
        <table style="width:auto; border: 5px solid rgb(255, 81, 217);" id="MATRIZ" align="center" valign="top">
                {% for i in euclidea%}
                <th>{{forloop.counter}}</th>
                {% endfor %}
    
                {% for i in euclidea %}
                <tr style="border: 5px solid rgb(255, 81, 217)">
                    <th>{{forloop.counter}}</th>
    
                    {% for j in i %}
                    {% if j == 0  %}
                    <td style="border: 5px solid rgb(255, 255, 255);"> {{j}}</td>
                    {% else %}
                    <td style="border: 5px solid rgb(255, 0, 255);"> {{j}}</td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </table>
      </div>

    </td>

    <td id="nested" valign="top" align="center">
<fieldset style="border: 1px solid rgb(253, 0, 211);">
    <div class="w-1/3 mx-auto">
      <form action="" method="POST">
          {%csrf_token %}
        <label for="umbral" class="text-xl block w-full text-center block mb-3">Umbral: </label>
        <div class="w-full">
            <input type="text" name="umbral" onkeypress="return Numeros(event)" class="border-gray-300 border-2 px-5 py-2 rounded-md block mx-auto w-1/2 outline-none text-gray-400">
        </div>
        <button type="submit" class="bg-pink-500 text-white py-2 px-3 font-bold rounded-lg hover:bg-pink-400 block mx-auto mt-3 block">Umbral</button>
      </form>
    </div>
</fieldset>



<div style="width:350px; height:6500px; overflow: scroll;" align="CENTER">
  <table align="CENTER">
      <th style="border: 5px solid rgb(253, 2, 241);">Iniciales</th>
      <th style="border: 5px solid rgb(255, 255, 255);">Finales</th>
      <th style="border: 5px solid rgb(253, 2, 241);">Distancia</th>
      <th style="border: 5px solid rgb(255, 255, 255);">TRUE/FALSE</th>


      {% for i in euclidea %} {% for j in i %} {% if forloop.counter >= forloop.parentloop.counter %}

      <tr class="px-10 w-full" align="center">
          <td style="border: 5px solid rgb(255, 255, 255);">{{forloop.parentloop.counter}}</td>
          <td style="border: 5px solid rgb(253, 2, 241);">{{forloop.counter}}</td>
          <td style="border: 5px solid rgb(255, 255, 255);">{{j}}</td>
          <td style="border: 5px solid rgb(253, 2, 241);">{% if j > umbral %} FALSE {% else %} TRUE {% endif %}</td>
      </tr>

      {% endif %} {% endfor %} {% endfor %}

  </table>

</div>
















    </td>
</table>
 
{% endblock contenido %}
</body>
</html>

sintactico/templates/sintactico/sintactico.html
{% extends 'home/index.html' %}
{% block contenido %}
    <h1 style="color:  rgb(89, 61, 248);"><font size="6">¿QUE ES EL RECONOCIMIENTO DE PATRONES SINTACTICO ESTRUCTURAL?</h1>
    <p align="justify"><font size="5" style="color:  rgb(0, 36, 136);" >El reconocimiento de patrones es la ciencia que se ocupa de los procesos sobreingeniería, 
        computación y matemáticas relacionados con objetos físicos y/o abstractos, con el propósito 
        de extraer información que permita establecer propiedades de o entre conjuntos de dichos objetos.
        Reconocimiento Sintáctico de Patrones.- Este  enfoque se basa en encontrar las relaciones
        estructurales que guardan los objetos de estudio,  utilizando la teoría de lenguajes formales. El objetivo
        es construir una gramática que describa la estructura del universo de objetos.</p>

        <p><center><img src="https://almacenamientoit.ituser.es/files/201810/iartificial.jpg" width="400" height="200" ></center></p>

{% endblock contenido %}